### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by n8gallagher** [n8gallagher/fotopx#2]
# PA Review: User Auth
## Functionality
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] If logged in, should not be able to visit `/login` or `/signup`
- [x] If logged in, should be able to refresh the page and still be logged in
- [x] Demo user can log in

**Comment by n8gallagher** [comment]
I took care of the highlighting issues on all the buttons and changed all the cursors for the submit and buttons.

**Comment by n8gallagher** [comment]
update: can login as demo user from signup. adjusted routes for splash and login.

**Comment by n8gallagher** [comment]
added home page and added message in nav to identify logged in user.

**Comment by mkayys** [comment]
![Screen Shot 2020-08-24 at 11 06 00 AM](https://user-images.githubusercontent.com/48598856/91081013-50995700-e5fb-11ea-9ec2-d6b334d37798.png)
- Your home image isn't rendering
- After logging in, can't see a logout and end up stuck on the root page.

**Comment by n8gallagher** [comment]
ok, i am not sure what went wrong, I'm pushing up my latest changes and i will test before assigning the issue back to you

**Comment by n8gallagher** [comment]
I figured out why the image was not rendering, fixed!

**Comment by mkayys** [comment]
Having a 500 Internal Server error when trying to logout. I was testing the demo user.

**Comment by n8gallagher** [comment]
Thanks Michelle I think it was very unfortunate timing I was also clicking around on the site at the time. Now it seems to be working.

**Comment by mkayys** [comment]
looks good!
